name: auto-update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'
jobs:

  iptvcat-scraper:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Install Dependencies
        run: npm install
      - name: Run Scrapper
        run: npm start
          folder: data
          clean: false
