name: auto-update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'
jobs:

  iptvcat-scraper:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Install Dependencies
        run: npm install
      - name: Run Scrapper
        run: npm start
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: data
          clean: false
